// Generated by scripts/generate-blur.ts — run `npm run media:blur` after adding images.
export const blurData: Record<string, string> = {
  '/images/atmosphere/candles.jpg': 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoQAAYAA4BaJQBOgBtddgUAAP7s2XuXdFNoS1dpnnLDFMDSHLWuME1ptwAAAA==',
  '/images/atmosphere/linen.jpg': 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoOABAAA4BaJZgCdADOnqAs+XAAAP5rc7XM3ch4p8sbZjL+Q0PMN1EJBzvNmiJZx28ZBxKr8AA=',
  '/images/atmosphere/stone-window.jpg': 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAkAA4BaJYgC7ACBno4AAP7t1f+qim612lzlXP/I9/16eEwxmgo5vBNQBwAA',
  '/images/atmosphere/white-wine.jpg': 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoPABAAA4BaJQBOgBjrGG7hy9AA+6W9mOldLpFbhS0jLNXZW0vyqmzyHJqhdm7sWqbYoAAA',
  '/images/atmosphere/window.jpg': 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAYAA4BaJQBOgBMvLaVYAP7ybQr1CQk9x9nchNK4DTDq0aMM29i3vybcIAAA',
  '/images/atmosphere/wine.jpg': 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoOABAAA4BaJYgCdAEHKIN79P0AAP5N2wG3n2fdRGUA8j/jXDG0kazuiKtl2a5xNjwmuNF4OtjNX7kgAAA=',
  '/images/dishes/burrata.jpg': 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQABAAA4BaJZACdADDGwhHcwAA/soSVCLb5nBRu3xoPFFSYqbBPNWYQ9cG7W4Ly/xMtC7Fw8/gAAAA',
  '/images/dishes/fuzi-truffle.jpg': 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoQABAAA4BaJQBOgBa1MjbaQAD+7QjlWDxV58F+Im4cT5u6MydflRRAnIIfL8zxGGtyJuwMAAA=',
  '/images/dishes/panna-cotta.jpg': 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoQABAAA4BaJQBOgBcGpOdJOZqAAP7ybQr1CQk9x9ncjcxj9dbdqWsNIbIt238MQ8joV/y3zbu1vaNAAAA=',
  '/images/dishes/pasticada.jpg': 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAQCdASoQABAAA4BaJQBOgBMtsQAA/gm7AdGsVC8RwRMu1Ro8qBXeCUlzylcgjumSWc5BlzdEHvaYerEm2lj1k7xAAA==',
  '/images/dishes/tuna-tartare.jpg': 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoQABAAA4BaJYwC7ADNuOunzQAA/thMuC4qDT97wIf4cn9xqxKmHjj8+MfjLAktEvAAAA==',
  '/images/kitchen/chefs.jpg': 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoQAAkAA4BaJaQAAgcFofnwAADv3UaBI/Rq9Nk5APFMTtCzGszdUE1c6KAAAA==',
  '/images/kitchen/dough.jpg': 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoQAAkAA4BaJaQAAWYJHQAA/CH8JF+0OMeGUV9ItnTwL/MBL33MQAAA',
  '/images/kitchen/fire.jpg': 'data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACwAQCdASoQAAkAA4BaJaQAAuSAlYOgAP7xrVXdUH/SMe8HrhgAAA==',
  '/images/kitchen/hands.jpg': 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoQAAkAA4BaJaQAAltNfSAA/pULAoDeF8gl8dmdvJEq0Ob1pLXLAAAA',
  '/images/kitchen/poster.jpg': 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACQAQCdASoQAAkAA4BaJaQAAcozhIAA86OOme29Zc5NnrU4uBW7nUONn2ff0TAAAAA=',
};
