/**
 * Builds content/blur.ts: a tiny blurred preview (data URL) for every image in
 * public/images, so photos paint instantly as a soft placeholder instead of
 * leaving an empty box while the full file loads.
 *
 *   npm run media:blur
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = fileURLToPath(new URL('..', import.meta.url));
const dir = join(root, 'public/images');

const walk = (d: string): string[] =>
  readdirSync(d).flatMap((f) => {
    const p = join(d, f);
    return statSync(p).isDirectory() ? walk(p) : /\.(jpe?g|png|webp|avif)$/i.test(f) ? [p] : [];
  });

const entries: string[] = [];
for (const file of walk(dir).sort()) {
  const buf = await sharp(file).resize(16, 16, { fit: 'inside' }).blur(1.2).webp({ quality: 40 }).toBuffer();
  const key = '/' + relative(join(root, 'public'), file).split('\\').join('/');
  entries.push(`  '${key}': 'data:image/webp;base64,${buf.toString('base64')}',`);
}

writeFileSync(
  join(root, 'content/blur.ts'),
  `// Generated by scripts/generate-blur.ts — run \`npm run media:blur\` after adding images.\nexport const blurData: Record<string, string> = {\n${entries.join('\n')}\n};\n`,
);
process.stdout.write(`content/blur.ts: ${entries.length} images\n`);
